### ISSUE TITLE
admin portal

### ISSUE THREAD

**Issue by AbrorxonAloxonov** [xgp/keycloak-account-v1#4]

**Comment by AbrorxonAloxonov** [comment]
![image](https://github.com/xgp/keycloak-account-v1/assets/109734441/d69bf673-c5ab-4623-9081-d07ce7a095e5)

**Comment by AbrorxonAloxonov** [comment]
![image](https://github.com/xgp/keycloak-account-v1/assets/109734441/c3845695-886b-4c4a-b5ae-3d103e269cce)

**Comment by xgp** [comment]
@AbrorxonAloxonov I think you are looking for the Admin Portal repo https://github.com/p2-inc/phasetwo-admin-portal 
Please post issues there.
